# Documentation: https://github.com/roots/trellis#mail
mail_smtp_server: smtp.mandrillapp.com:587
mail_admin: admin@webpeak.com
mail_hostname: webpeak.com
mail_user: jwall@webpeak.com
mail_password: ZVKhUWevdOCYR6623GlxqQ
